Feature/kirkstone community platforms
rdkcentral/meta-vendor-raspberrypi-release pull request #73
Opened 2024-10-23 15:13 UTC by leenaS-d

2024-10-23 17:49 UTC, mhughesacn requested changes
See comments.  Also, if enabling fdk-aac as a commercial component, you need to be certain that if images are distributed, recipients are sure of their license obligations.  (e.g. https://developer.garmin.com/open-source/fraunhofer/).

2024-10-23 17:49 UTC, mhughesacn commented on recipes-workaround/firebolt-native-sdk/firebolt-native-sdk.bb
> +LICENSE = "CLOSED"
Should  not have an RDK-licensed component referenced in an OSS metalayer.

2024-10-23 17:49 UTC, mhughesacn commented on recipes-workaround/mountutils/mountutils.bb
> +# COMCAST C O N F I D E N T I A L AND PROPRIETARY
Recipes do not have a header, especially a confidential one.

2024-10-23 17:49 UTC, mhughesacn commented on recipes-workaround/rdk-gstreamer-utils-platform/rdk-gstreamer-utils-rpi_git.bb
> +LICENSE = "CLOSED"
CLOSED license in an opensourced repo?

2024-10-23 17:49 UTC, mhughesacn commented on recipes-workaround/storagemanager/storagemanager_git.bb
> +# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
- Confidential header in opensourced repo?
- Licensed component in opensourced repo?  Thisnrecipe doesn't belong here.

2024-10-31 15:47 UTC, mhughesacn commented
Hi LeenaS, Arun: As Blackduck is now passing and all the awkward findings are gone, I don't have any comments here.  Thanks for making the changes.

2024-12-04 16:07 UTC, closed without merging

2024-12-04 16:07 UTC, leenaS-d commented
abandon